<?php
return [
    'home_note_1' => 'With the desire to bring to the market products and services of international standards and completely new experiences in modern lifestyle, in any field,
     HLYgroup proves its pioneering and leading role. changes in consumption trends.',

    'home_title_1' => "Pioneering<br/>Field",

    'about_note_1' => "Is a joint stock company, established on January 4, 2023 in Hanoi City, Vietnam. With the founding participation of 7 members, coming from many fields such as: Real Estate, Lawyer, Southern Medicine, Agriculture and Construction forming a common roof is the HLY ecosystem. On January 12, 2023,
    Trieu Gia HLY Joint Stock Company was born, formerly known as Trieu Gia Co.,
    Ltd. Model of joining the big family of HLY ecosystem through the model of stake cross-linking.",

    'about_note_2' => "With the desire to bring everyone, every family have health,
    Environmentally friendly green food and a happy and healthy life.",

    'about_title_1' => "Staff",
    'about_title_2' => "Mission vision <br/> and Core values",
    'about_title_3' => "For<br/> Customer",

    'about_title_1_note' => "At HLY as well as in the HLY ecosystem, each position will have its own standards,
    However, all members meet the requirements: have professional qualifications, are enthusiastic about the profession, have a high sense of responsibility and discipline...",

    'about_title_2_note' => "Vision with everyone to build happiness for themselves and for the community.
    Mission to awaken awareness and take action to take care of yourself and everyone's health; Creative application of Southern medicine knowledge to take care of Men...",

    'about_title_3_note' => "Creating products and services of optimal quality, bringing satisfaction to customers at the highest level",

    'about_brand_note' => 'With the desire to bring to the market products and services of international standards and experiences
                    completely new experience in modern lifestyle, in any field HLYgroup has proved its role
                    pioneering, leading the change in consumption trends.',

    //green tech              
    'about_green_tech_1' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the needs of tourists.",
    'about_green_tech_2' =>"With a large potential and increasing demand from tourists, the market for developing health tourism products is quite abundant. However, in many localities, health tourism products have not been fully exploited or developed to their full potential, which has resulted in a lack of differentiation and attraction for tourists.",
    'about_green_tech_3' =>"This reality requires closer coordination between the tourism industry, localities, and businesses. It also requires active innovation, product improvement, and the creation of attractive features for this highly potential form of tourism.",
    'about_green_tech_4' =>"Enhancing the quality of services and products.",
    'about_green_tech_5' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the trends and needs of tourists.",
    'about_green_tech_6' =>"Therefore, according to some experts, one of the solutions for developing health care tourism and enhancing competitiveness for destinations in Vietnam, in general, and each locality, in particular, is to develop high-quality products with high added value based on researching the demands and preferences of domestic and international tourist markets.",
    'about_green_tech_7' =>"Developing products to meet sustainable development requirements must adhere to principles that respect natural and local cultural factors. Planning and investing in the development of health care tourism products should focus on leveraging each locality's tourism resources, while also strengthening linkages between regions and creating a value chain of interconnected services to enhance the quality of products introduced to tourists.",
    'about_green_tech_8' =>"Master Nguyen Hoang Mai, from the Institute for Tourism Development Research (Vietnam National Administration of Tourism), asserts that Vietnam has great potential for developing health care tourism with traditional oriental medicine treatments, natural resources such as hot mineral springs and natural landscapes, as well as cultural and social resources.",
    'about_green_tech_9' =>"In addition, the tourism accommodation system with standard health care facilities is also a strength. Destinations such as Hoi An, Nha Trang, Phu Quoc, and Ho Chi Minh City attract a significant number of tourists for health care purposes or medical treatment. However, on the world map of health care tourism, Vietnam's presence is still quite modest.",    
    'about_green_tech_10' =>"Therefore, to develop the market for this highly potential form of tourism, the Vietnamese tourism industry needs to improve the quality of existing health care tourism services and ensure that they meet standards and criteria for the health and safety of tourists.",  
    'about_green_tech_11' =>"At the same time, the tourism industry should develop a system of health care tourism products and services that are suitable for each segment of the tourist market based on age, cultural background, and create a unique Vietnamese identity that is competitive with other countries in the region.",    
    'about_green_tech_12' =>"From the perspective of a tour service company, Ms. Trieu Thi Hoa from PYS Tourist Company proposes that functional units need to have specific orientation and planning for effective, long-term, and sustainable development of health care tourism products. Quality management of health care tourism products is a top priority, requiring coordination with specialized agencies with authority in assessing technical quality of health care services to ensure the requirements for sustainable tourism development.",    
    'about_green_tech_13' =>"In terms of specific solutions for developing health care tourism in localities with great potential such as Ba Ria-Vung Tau, Ms. Pham Thi Thanh Huyen from the National Economics University suggests that localities should strongly develop tours that combine resort vacations with health care services, such as meditation and yoga tours in pristine and tranquil natural landscapes.",   
    'about_green_tech_14' =>"The province continues to diversify its resort infrastructure, such as developing hot mineral bath areas, skylight areas, and mineral mud bath areas. Ba Ria-Vung Tau also diversifies its health care tourism products that complement the locality's characteristic sea bathing, organize activities using healthy and organic food, saunas, relaxation, hot spring baths, and other complementary types of services to enrich tourists' experiences when participating in health care services.",    
    'about_green_tech_15' =>"Enterprises and functional units should enhance the construction and implementation of all-inclusive health care tourism programs and carry out campaigns to promote the image of health care tourism in Ba Ria-Vung Tau.",

 

    //trade in service
    'about_trade_service_1' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the needs of tourists.",
    'about_trade_service_2' =>"With a large potential and increasing demand from tourists, the market for developing health tourism products is quite abundant. However, in many localities, health tourism products have not been fully exploited or developed to their full potential, which has resulted in a lack of differentiation and attraction for tourists.",
    'about_trade_service_3' =>"This reality requires closer coordination between the tourism industry, localities, and businesses. It also requires active innovation, product improvement, and the creation of attractive features for this highly potential form of tourism.",
    'about_trade_service_4' =>"Enhancing the quality of services and products.",
    'about_trade_service_5' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the trends and needs of tourists.",
    'about_trade_service_6' =>"Therefore, according to some experts, one of the solutions for developing health care tourism and enhancing competitiveness for destinations in Vietnam, in general, and each locality, in particular, is to develop high-quality products with high added value based on researching the demands and preferences of domestic and international tourist markets.",
    'about_trade_service_7' =>"Developing products to meet sustainable development requirements must adhere to principles that respect natural and local cultural factors. Planning and investing in the development of health care tourism products should focus on leveraging each locality's tourism resources, while also strengthening linkages between regions and creating a value chain of interconnected services to enhance the quality of products introduced to tourists.",
    'about_trade_service_8' =>"Master Nguyen Hoang Mai, from the Institute for Tourism Development Research (Vietnam National Administration of Tourism), asserts that Vietnam has great potential for developing health care tourism with traditional oriental medicine treatments, natural resources such as hot mineral springs and natural landscapes, as well as cultural and social resources.",
    'about_trade_service_9' =>"In addition, the tourism accommodation system with standard health care facilities is also a strength. Destinations such as Hoi An, Nha Trang, Phu Quoc, and Ho Chi Minh City attract a significant number of tourists for health care purposes or medical treatment. However, on the world map of health care tourism, Vietnam's presence is still quite modest.",    
    'about_trade_service_10' =>"Therefore, to develop the market for this highly potential form of tourism, the Vietnamese tourism industry needs to improve the quality of existing health care tourism services and ensure that they meet standards and criteria for the health and safety of tourists.",  
    'about_trade_service_11'=>"At the same time, the tourism industry should develop a system of health care tourism products and services that are suitable for each segment of the tourist market based on age, cultural background, and create a unique Vietnamese identity that is competitive with other countries in the region.",    
    'about_trade_service_12' =>"From the perspective of a tour service company, Ms. Trieu Thi Hoa from PYS Tourist Company proposes that functional units need to have specific orientation and planning for effective, long-term, and sustainable development of health care tourism products. Quality management of health care tourism products is a top priority, requiring coordination with specialized agencies with authority in assessing technical quality of health care services to ensure the requirements for sustainable tourism development.",    
    'about_trade_service_13'=>"In terms of specific solutions for developing health care tourism in localities with great potential such as Ba Ria-Vung Tau, Ms. Pham Thi Thanh Huyen from the National Economics University suggests that localities should strongly develop tours that combine resort vacations with health care services, such as meditation and yoga tours in pristine and tranquil natural landscapes.",   
    'about_trade_service_14'=>"The province continues to diversify its resort infrastructure, such as developing hot mineral bath areas, skylight areas, and mineral mud bath areas. Ba Ria-Vung Tau also diversifies its health care tourism products that complement the locality's characteristic sea bathing, organize activities using healthy and organic food, saunas, relaxation, hot spring baths, and other complementary types of services to enrich tourists' experiences when participating in health care services.",    
    'about_trade_service_15' =>"Enterprises and functional units should enhance the construction and implementation of all-inclusive health care tourism programs and carry out campaigns to promote the image of health care tourism in Ba Ria-Vung Tau.",

    //green food
    'about_green_food_1' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the needs of tourists.",
    'about_green_food_2' =>"With a large potential and increasing demand from tourists, the market for developing health tourism products is quite abundant. However, in many localities, health tourism products have not been fully exploited or developed to their full potential, which has resulted in a lack of differentiation and attraction for tourists.",
    'about_green_food_3' =>"This reality requires closer coordination between the tourism industry, localities, and businesses. It also requires active innovation, product improvement, and the creation of attractive features for this highly potential form of tourism.",
    'about_green_food_4' =>"Enhancing the quality of services and products.",
    'about_green_food_5' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the trends and needs of tourists.",
    'about_green_food_6' =>"Therefore, according to some experts, one of the solutions for developing health care tourism and enhancing competitiveness for destinations in Vietnam, in general, and each locality, in particular, is to develop high-quality products with high added value based on researching the demands and preferences of domestic and international tourist markets.",
    'about_green_food_7' =>"Developing products to meet sustainable development requirements must adhere to principles that respect natural and local cultural factors. Planning and investing in the development of health care tourism products should focus on leveraging each locality's tourism resources, while also strengthening linkages between regions and creating a value chain of interconnected services to enhance the quality of products introduced to tourists.",
    'about_green_food_8' =>"Master Nguyen Hoang Mai, from the Institute for Tourism Development Research (Vietnam National Administration of Tourism), asserts that Vietnam has great potential for developing health care tourism with traditional oriental medicine treatments, natural resources such as hot mineral springs and natural landscapes, as well as cultural and social resources.",
    'about_green_food_9' =>"In addition, the tourism accommodation system with standard health care facilities is also a strength. Destinations such as Hoi An, Nha Trang, Phu Quoc, and Ho Chi Minh City attract a significant number of tourists for health care purposes or medical treatment. However, on the world map of health care tourism, Vietnam's presence is still quite modest.",    
    'about_green_food_10' =>"Therefore, to develop the market for this highly potential form of tourism, the Vietnamese tourism industry needs to improve the quality of existing health care tourism services and ensure that they meet standards and criteria for the health and safety of tourists.",  
    'about_green_food_11' =>"At the same time, the tourism industry should develop a system of health care tourism products and services that are suitable for each segment of the tourist market based on age, cultural background, and create a unique Vietnamese identity that is competitive with other countries in the region.",    
    'about_green_food_12' =>"From the perspective of a tour service company, Ms. Trieu Thi Hoa from PYS Tourist Company proposes that functional units need to have specific orientation and planning for effective, long-term, and sustainable development of health care tourism products. Quality management of health care tourism products is a top priority, requiring coordination with specialized agencies with authority in assessing technical quality of health care services to ensure the requirements for sustainable tourism development.",    
    'about_green_food_13' =>"In terms of specific solutions for developing health care tourism in localities with great potential such as Ba Ria-Vung Tau, Ms. Pham Thi Thanh Huyen from the National Economics University suggests that localities should strongly develop tours that combine resort vacations with health care services, such as meditation and yoga tours in pristine and tranquil natural landscapes.",   
    'about_green_food_14' =>"The province continues to diversify its resort infrastructure, such as developing hot mineral bath areas, skylight areas, and mineral mud bath areas. Ba Ria-Vung Tau also diversifies its health care tourism products that complement the locality's characteristic sea bathing, organize activities using healthy and organic food, saunas, relaxation, hot spring baths, and other complementary types of services to enrich tourists' experiences when participating in health care services.",    
    'about_green_food_15' =>"Enterprises and functional units should enhance the construction and implementation of all-inclusive health care tourism programs and carry out campaigns to promote the image of health care tourism in Ba Ria-Vung Tau.",

    //VN medicine
    'about_VN_medicine_1' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the needs of tourists.",
    'about_VN_medicine_2' =>"With a large potential and increasing demand from tourists, the market for developing health tourism products is quite abundant. However, in many localities, health tourism products have not been fully exploited or developed to their full potential, which has resulted in a lack of differentiation and attraction for tourists.",
    'about_VN_medicine_3' =>"This reality requires closer coordination between the tourism industry, localities, and businesses. It also requires active innovation, product improvement, and the creation of attractive features for this highly potential form of tourism.",
    'about_VN_medicine_4' =>"Enhancing the quality of services and products.",
    'about_VN_medicine_5' =>"Developing effective health care tourism contributes to diversifying products associated with the rational use of tourism resources, enhancing the attractiveness of destinations, and better meeting the trends and needs of tourists.",
    'about_VN_medicine_6' =>"Therefore, according to some experts, one of the solutions for developing health care tourism and enhancing competitiveness for destinations in Vietnam, in general, and each locality, in particular, is to develop high-quality products with high added value based on researching the demands and preferences of domestic and international tourist markets.",
    'about_VN_medicine_7' =>"Developing products to meet sustainable development requirements must adhere to principles that respect natural and local cultural factors. Planning and investing in the development of health care tourism products should focus on leveraging each locality's tourism resources, while also strengthening linkages between regions and creating a value chain of interconnected services to enhance the quality of products introduced to tourists.",
    'about_VN_medicine_8' =>"Master Nguyen Hoang Mai, from the Institute for Tourism Development Research (Vietnam National Administration of Tourism), asserts that Vietnam has great potential for developing health care tourism with traditional oriental medicine treatments, natural resources such as hot mineral springs and natural landscapes, as well as cultural and social resources.",
    'about_VN_medicine_9' =>"In addition, the tourism accommodation system with standard health care facilities is also a strength. Destinations such as Hoi An, Nha Trang, Phu Quoc, and Ho Chi Minh City attract a significant number of tourists for health care purposes or medical treatment. However, on the world map of health care tourism, Vietnam's presence is still quite modest.",    
    'about_VN_medicine_10' =>"Therefore, to develop the market for this highly potential form of tourism, the Vietnamese tourism industry needs to improve the quality of existing health care tourism services and ensure that they meet standards and criteria for the health and safety of tourists.",  
    'about_VN_medicine_11' =>"At the same time, the tourism industry should develop a system of health care tourism products and services that are suitable for each segment of the tourist market based on age, cultural background, and create a unique Vietnamese identity that is competitive with other countries in the region.",    
    'about_VN_medicine_12' =>"From the perspective of a tour service company, Ms. Trieu Thi Hoa from PYS Tourist Company proposes that functional units need to have specific orientation and planning for effective, long-term, and sustainable development of health care tourism products. Quality management of health care tourism products is a top priority, requiring coordination with specialized agencies with authority in assessing technical quality of health care services to ensure the requirements for sustainable tourism development.",    
    'about_VN_medicine_13'=>"In terms of specific solutions for developing health care tourism in localities with great potential such as Ba Ria-Vung Tau, Ms. Pham Thi Thanh Huyen from the National Economics University suggests that localities should strongly develop tours that combine resort vacations with health care services, such as meditation and yoga tours in pristine and tranquil natural landscapes.",   
    'about_VN_medicine_14' =>"The province continues to diversify its resort infrastructure, such as developing hot mineral bath areas, skylight areas, and mineral mud bath areas. Ba Ria-Vung Tau also diversifies its health care tourism products that complement the locality's characteristic sea bathing, organize activities using healthy and organic food, saunas, relaxation, hot spring baths, and other complementary types of services to enrich tourists' experiences when participating in health care services.",    
    'about_VN_medicine_15' =>"Enterprises and functional units should enhance the construction and implementation of all-inclusive health care tourism programs and carry out campaigns to promote the image of health care tourism in Ba Ria-Vung Tau.",

    'about_brand_title_1' =>"Brand for bone and joint health care, recovery after injury",
    'about_brand_title_2' =>"Brand for bone and joint health care, recovery after injury",
    'about_brand_title_3' =>"Brand for bone and joint health care, recovery after injury", 
    'about_brand_title_4' =>"Brand for bone and joint health care, recovery after injury", 

    'about_brand_introduce' =>"Vingroup is a place where outstanding people of the Vietnamese nation and international colleagues gather - those who possess disciplined thoughts and actions, talents and courage, love for their country and national pride, kindness and a determined spirit to work resolutely and thoroughly towards noble goals.",

    'about_company_include' => "Social Joint Stock Company HLY with 3 pioneering technology groups including",
    'about_brand_power' => "The overall three core business sectors and the collective strength of 10 member companies",
    'about_brand_partner' =>"FPT Software is a strategic partner in deploying smart factory for Jullie Sandue",
    'about_brand_partner_1' =>"FPT is an important strategic partner in advising, training, and implementing digital transformation for leading corporations and organizations globally and in Vietnam across various industries",

    'about_annual_gerenal_meeting_1'=>"Resolutions and minutes of the 2022 general meeting of shareholders",
    'about_annual_gerenal_meeting_2'=>"Notice of personnel change of the Board of Directors",
    'about_information_1'=>"Consolidated financial statements for the third quarter of 2022",
    'about_information_2'=>"Report on business results for the third quarter of 2022",
    'about_goverance_company_1'=>"Regulations on information disclosure at FPT company",
    'about_goverance_company_2'=>"Company rules",
    'about_goverance_company_3'=>"Governance Regulations",

    'about_welcome_recruitment'=>"We believe that honesty is a necessary starting point for any good relationship.",

    'about_heading_contact'=>"To learn more about HLY, its consulting experts, services provided, and potential opportunities for development evaluation, we would be delighted to connect with your business.",
    'about_heading_form_contact'=>"Please fill out the form below to receive more information about our services provided.",
    'about_question_form_contact'=>"The specific details about the question/issue that needs to be addressed.",

];
